[ALPS08631203] fix build error about include file changed
[Description]
Fix build error according to Commit "6fe236d7" (Merge 3cb9871f8160 ("Merge tag urgent-rcu.2024.01.24a of https://github.com/neeraju/linux") into android-mainline)

../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_epaelna.c:156:34: error: incomplete definition of type struct device_node
  156 |                 strncpy(result.part_name[i], np->name,
      |                                              ~~^
../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_module.c:113:31: error: variable has incomplete type struct platform_driver
  113 | static struct platform_driver connfem_plat_drv = {
      |                               ^
../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_epaelna.c:194:8: error: call to undeclared function of_property_read_u32; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  194 |         err = of_property_read_u32(np, CFM_DT_PROP_VID, &value);
      |               ^
../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_module.c:795:57: error: incomplete definition of type struct platform_device
k(  f795 |         if (of_match_device(of_match_ptr(connfem_of_ids), &pdev->dev)) {
      |                                                            ~~~~^
../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_dt_parser.c:180:44: error: incomplete definition of type struct platform_device
  180 |                 ((struct connfem_context_ops *)cfm)->pdev->dev.of_node;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
../vendor/mediatek/kernel_modules/connectivity/connfem/connfem_sku.c:187:29: error: variable has incomplete type struct of_phandle_iterator
  187 |         struct of_phandle_iterator it;
      |                                    ^
[Test]
Build and Boot up

MTK-Commit-Id: 6c2892c957a62cf31bab91cb458bbeba122c089f

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Ie4282f08f363d959b952f9f83fe3a1716093d69e