[ALPS08490829] connfem: fix of_gpio_named_count build breaks
Fix the build breaks caused by
commit c7835652a85d ("gpiolib: of: stop exporting of_gpio_named_count()")

Errors:
connfem/connfem_dt_parser.c:495:8: error: call to undeclared function of_gpio_named_count; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 52cd4927d5e5b67900a8fc3c3ea505b76dbb19cc

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS08490829
Feature: Kernel SI Operation
Change-Id: I0a2e85321aed2f36346b7ce65484d3262689bbd2